### ISSUE TITLE
in browser

### ISSUE THREAD

**Issue by tgkprog** [joelvh/json2json#14]
hi, i'm no JS expert and do not have node. Is there a way to just give us / commit to the repo:
1. Sysmo.js
2. TemplateConfig.js 
3. ObjectTemplate.js

So we can use it without any other steps? And a full blown exampole - html page with a static json that gets transformed on some template - a full browser example? Thank you

**Comment by joelvh** [comment]
The code is pretty straight-forward. You could likely compile each of those CoffeeScript files to JavaScript just using the "Run CoffeeScript" feature on their website:

http://coffeescript.org/

Paste in the code for each file, then copy the JavaScript output and save. In an HTML file, link to those JavaScript files like you normally would. Then how you use the object model from there, is up to you.

**Comment by fabianTMC** [comment]
This is becoming a headache in my deployment process. Could we possibly add a hook to compile the coffeescript files into javascript using the `coffee -c *.coffee` command and add it to the ./lib folder or alternately a build/ folder?
