### ISSUE TITLE
Array support

### ISSUE THREAD

**Issue by lpww** [joelvh/json2json#22]
Hey I really like your module for json mapping! It's very flexible and powerful when dealing with objects. However as far as I can tell there is not much support for arrays. I read that aggregate can be used to filter arrays but when I tried that the filtered results were converted to an object. 

I see in the readme that an object to array functionality is in the todo list. What are the plans for that? What other array features will be supported?

**Comment by joelvh** [comment]
@lpww can you see if the feature you're looking for was recently merged? Otherwise, comment on the issue you're referring to. Sounds like it shouldn't take much to fix what you're seeing, but may be tricky to track down.

**Comment by lpww** [comment]
The last release was Feb 18th and I've definitely installed the latest version since then. Here are some of the issues I've been running into with this.

1a. In 'array mode' (enabled when object[path] points to an array) aggregate iterates over the objects inside the array and not the array itself. I'm not sure if this is the intended behavior but it's not clear how to use this to filter an array (documentation says this is possible)
1b. Aggregate documentation is not clear, please provide an example of how to use it to filter an array

2.  Choose does not work in array mode. Take the following template:

```
{
    path: '.',
    as: {
        shop: {
            path: 'shop',
            as: {
                name: 'name',
                products: {
                    choose: ['products'], 
                    as: {
                        products: 'products' // shop is an object so this lookup is defined on the root of the input
                    }
                }
            }
        }
    }
}

```
What happens if I try to do the same thing for an array of objects?

```
{
    path: '.',
    as: {
        shops: {
            path: 'shops',
            as: {
                name: 'name',
                products: {
                    choose: ['products'],
                    as: {
                        products: 'products' // shops is an array so this lookup is undefined for some reason
                    }
                }
            }
        }
    }
}
```
Products is now undefined. It is entirely possible that I am approaching this wrong. If that is the case please indicate the proper way to inject data from the root input when dealing with arrays

**Comment by lpww** [comment]
@joelvh I've looked more into this and I think the choose issue is not related to arrays, I can't get it to work for objects either. Am I doing something wrong here?
