### ISSUE TITLE
Nesting templates

### ISSUE THREAD

**Issue by lpww** [joelvh/json2json#23]
I would love the ability to quickly and easily nest templates. Have you thought about this feature at all? It's a requirement for a project I'm working on. If it would be valuable I can look into implementing it as a feature of json2json?

**Comment by joelvh** [comment]
@lpww I haven't thought of that, but sounds interesting. Definitely will consider a PR if you make the update. Can you describe the implementation on this ticket further?

**Comment by lpww** [comment]
I have data that might have a couple of different paths depending on the use case. The way j2j is set up right now I would require a different template for each use case. It would be nice to be able to make a template once and 'reuse it somehow as part of another template. I've been thinking about this though and I don't know if this feature is something that should really be supported by your module. It might be better as a separate service that builds a full template and passes that into j2j. If there is interest I can certainly think more about an approach for including it as a feature here.

**Comment by joelvh** [comment]
@lpww have you made any enhancements around this?

**Comment by lpww** [comment]
No, I ended up duplicating the templates at the time but am no longer using the library

**Comment by joelvh** [comment]
OK thanks @lpww
