### ISSUE TITLE
Convert array to string and Join two array elements

### ISSUE THREAD

**Issue by rpamul** [joelvh/json2json#27]
Hi,
I'm trying to achieve the following typical use-case with coffee templates.

Input data
**const inputData = {'key1': ['Hello'], 'key2': ['world']};**

expecting output after transformation
**const outPutData = {'wishList': ['Hello', 'World'], 'message': 'Hello'};**

are there anyone achieved/tried the above use-case with coffee template !

**Comment by joelvh** [comment]
@rpamul maybe try using `aggregate` and `format` together?
