### ISSUE TITLE
npm install json2json@0.2.4 does not contain ignoreEmpty functionality

### ISSUE THREAD

**Issue by slmmm** [joelvh/json2json#28]
I am in need of the ability to have a transformed object include properties where the source is null.  I attempted to specify a template with "ignoreEmpty": false, but have not seen the null valued properties included in the transformed json.

I installed json2json using npm and attempted specifying the version as well (e.g. npm install json2json@0.2.4) but still do not have any code references in the node_modules lib files that refer to "ignoreEmpty" configuration.  
I downloaded a zip of the Code source here on git, and I do see the reference to "ignoreEmpty", as well as being able to get null valued properties in the transformed object (this after copying the source to modules folder).

How can I use npm install to get the correct version of json2json containing this functionality?

**Comment by joelvh** [comment]
@slmmm I published v2.0.5 to NPM. See if that works for you.

**Comment by joelvh** [comment]
@slmmm merged #21 and released v0.2.6 to NPM

**Comment by slmmm** [comment]
Yes, thank you for the publish - v0.2.6 worked as expected.

**Comment by joelvh** [comment]
ok, great @slmmm - I'm curious - what are you using this project for?

**Comment by slmmm** [comment]
Hi @joelvh - I first used json2json about 5 years ago and originally chose it primarily for two reasons: (a) ease of use in defining a template, and (b) ability to work with transforming arrays.  Recently, I chose to use json2json again, after looking at a handful similar libraries, because it continues to be reliable and easy to use, can do both simple and complex transforms (allowing for current need and future possibilities), and most importantly, we needed to be able configure a transformed object to contain all properties even when they were null.

**Comment by joelvh** [comment]
Thanks for the feedback @slmmm - I'm glad this library has been helpful.
