### ISSUE TITLE
Data-driven Formatting Example

### ISSUE THREAD

**Issue by aaronkaka** [joelvh/json2json#4]
Would you provide an example in the documentation of how to format the output conditionally based on the value of a specific key?  I'm attempting to perform data-driven styling, but having difficulty with the format function.

For example:

var tmpl = {
    path: 'response.docs',
    format: function (node, value, key) {

// pseudo-code to express the desired feature
// if (some.key.value > 50)
//       return {color.value = 'red'};
     },
    as: {
        title: 'Title',
        effortDriven: 'effortDriven',
        color: 'blue'
    }
};

**Comment by joelvh** [comment]
@aaronkaka did you ever figure this out? Is there an update to the README or elsewhere you'd like to submit?

**Comment by joelvh** [comment]
@aaronkaka anything you can contribute here?
